apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w8zain2bp-go 
  janus-idp.io/tekton: w8zain2bp-go
  backstage.io/kubernetes-id: w8zain2bp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w8zain2bp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml